-- Ejecutar conectado a la base de datos existente biblioteca_fx.
CREATE TABLE IF NOT EXISTS empleado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    cedula VARCHAR(30) NOT NULL UNIQUE,
    correo VARCHAR(150) UNIQUE,
    telefono VARCHAR(30),
    cargo VARCHAR(100),
    departamento VARCHAR(100) NOT NULL,
    salario NUMERIC(12, 2) NOT NULL CHECK (salario >= 0),
    fecha_contratacion DATE NOT NULL,
    estado VARCHAR(10) NOT NULL CHECK (estado IN ('Activo', 'Inactivo'))
);

-- Registros de ejemplo. ON CONFLICT permite volver a ejecutar el archivo.
INSERT INTO empleado (nombres, apellidos, cedula, correo, telefono, cargo, departamento, salario, fecha_contratacion, estado)
VALUES
 ('Ana María', 'López Ruiz', '001-120590-0001A', 'ana.lopez@example.com', '8888-1001', 'Analista', 'Finanzas', 18500.00, '2022-03-14', 'Activo'),
 ('Carlos', 'Mendoza Silva', '001-081188-0002B', 'carlos.mendoza@example.com', '8888-1002', 'Desarrollador', 'Tecnología', 27000.00, '2021-07-01', 'Activo'),
 ('Daniela', 'Pérez Castro', '001-040295-0003C', 'daniela.perez@example.com', '8888-1003', 'Coordinadora', 'Recursos Humanos', 22000.00, '2023-01-09', 'Activo'),
 ('José Miguel', 'Ramírez Torres', '001-221080-0004D', 'jose.ramirez@example.com', '8888-1004', 'Vendedor', 'Ventas', 16500.00, '2020-11-23', 'Inactivo'),
 ('María Fernanda', 'Gutiérrez León', '001-150699-0005E', 'maria.gutierrez@example.com', '8888-1005', 'Supervisora', 'Operaciones', 24000.00, '2022-09-05', 'Activo')
ON CONFLICT (cedula) DO NOTHING;

SELECT * FROM empleado ORDER BY id;
